### ISSUE TITLE
Add the 'User.Preferences' calls

### ISSUE THREAD

**Issue by blackboxlogic** [blackboxlogic/OsmApiClient#10]

**Comment by HarelM** [comment]
It will be best if you could link the relevant commit to the relevant issue.
This is easily done by referencing the issue number in the commit message.
You can also close the issue using a commit by writing Resolves #10, or Fixes #10.
relevant commit: 665139018e729da3f115733d604f129b457ac7d0
See here:
https://help.github.com/en/articles/closing-issues-using-keywords
Extremely useful :-)

**Comment by blackboxlogic** [comment]
Good to know for next time.
This issue was resolved by https://github.com/blackboxlogic/OsmApiClient/commit/665139018e729da3f115733d604f129b457ac7d0
