### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by blackboxlogic** [blackboxlogic/OsmApiClient#15]
Use the MSTest and split every operation to its own test by using `[TestInitialize]` and `[TestCleanup]` so that you can test every part of the API separately.

_Originally posted by @HarelM in https://github.com/blackboxlogic/OsmApiClient/issues/8#issuecomment-580110371_

**Comment by HarelM** [comment]
@blackboxlogic feel free to review my initial commit.
I admit, I got a bit lazy - in theory, every assert should have its own test, but I have grouped them a bit by topics.
P.S. every time this tests run a note is added without being deleted (to dev env, I know, but still)?

**Comment by blackboxlogic** [comment]
I don't mind lazy. I'll look at the test changes later today.
This performs _every_ operation, including updating elements. This is what the DEV environment is for. That's why:
``` c#
if (!Config["osmApiUrl"].Contains("dev")) throw new Exception("These tests modify data, and it looks like your running them in PROD, please don't");
```

**Comment by HarelM** [comment]
Ok, I'll see if I can check-in the auth tests as well, I think I'll add a comment in the test initialize so you can select which client to test since these tests should only run manually, I think...

**Comment by blackboxlogic** [comment]
It looks good to me. I'm trying to get the automation to run the tests before publishing the Nuget package. Once I have that, are you ready for v0.0.5 to be released?

**Comment by HarelM** [comment]
Sure :-)

**Comment by blackboxlogic** [comment]
Thank you for your work. Those two things had been bugging me (but not enough to do them).
https://www.nuget.org/packages/OsmApiClient/0.0.5

**Comment by HarelM** [comment]
I'll keep this one open until I commit the rest of the tests if you font mind. Should be today-tomorrow...

**Comment by blackboxlogic** [comment]
Of course, didn't realize there was more to come. Up the package version, merge to master, and you'll get a new nuget version published. No need to check with me.

**Comment by HarelM** [comment]
These are only tests, I don't plan to change the code, so I don't see a good reason to publish a new version.
I'm planning on deleting the functional tests project if it's OK with you...

**Comment by blackboxlogic** [comment]
Yes, that would be for the better. The auth tests need their credentials configurable, but preferably not checked in. One option: Github has a place where it stores repo secrets. Another option is a confirmation file which is ignored by git. Let me know if you don't have access or have questions.

Though I guess it's not the end of the world if DEV credentials get leaked.

**Comment by HarelM** [comment]
I agree, I added a comment in the test class to enter it manually and not check-in.
I'm guessing that for now (and probably forever :-)) it's probably only the two of us, so I don't expect a problem here - I prefer not to run these tests every commit so that not to spam dev OSM environment, but I'm open for suggestions...

**Comment by HarelM** [comment]
In other words, feel free to change it the way you like it and works for you...
