### ISSUE TITLE
Add request address to response logging

### ISSUE THREAD

**Issue by HarelM** [blackboxlogic/OsmApiClient#18]
There are situations where multiple requests are sent, some may fail.
If request are sent in parallel there's no way to know which request failed and which didn't.
Adding the address and method to the logging should solve this.

**Comment by blackboxlogic** [comment]
Adding the full address and http method seems like a lot of noise in the logs and it might be hard to pipe that information to each log statement. What do you think about adding thread numbers instead? For example:

```info: Tests[0]
      Testing unauthenticated client
info: Client[0]
      Thread 1 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/capabilities
info: Client[0]
      Thread 4 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 4 - Content-Type: application/xml; charset=utf-8
info: Client[0]
      Thread 4 - GET: https://master.apis.dev.openstreetmap.org/api/versions
info: Client[0]
      Thread 4 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 4 - Content-Type: application/xml; charset=utf-8
info: Client[0]
      Thread 4 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/map?bbox=-77.06719,38.90072,-77.001,38.98734
info: Client[0]
      Thread 5 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 5 - Content-Encoding: identity, Content-Disposition: attachment; filename="map.osm", Content-Type: text/xml; charset=utf-8
info: Client[0]
      Thread 5 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/node/964762
info: Client[0]
      Thread 5 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 5 - Content-Encoding: identity, Content-Type: text/xml; charset=utf-8
info: Client[0]
      Thread 5 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/way/53197
info: Client[0]
      Thread 5 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 5 - Content-Encoding: identity, Content-Type: text/xml; charset=utf-8
info: Client[0]
      Thread 5 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/way/53197/full
info: Client[0]
      Thread 5 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 5 - Content-Encoding: identity, Content-Type: text/xml; charset=utf-8
info: Client[0]
      Thread 5 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/relation/4294967296
info: Client[0]
      Thread 5 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 5 - Content-Encoding: identity, Content-Type: text/xml; charset=utf-8
info: Client[0]
      Thread 5 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/relation/4294967296/full
info: Client[0]
      Thread 5 - Request succeeded: OK-OK
dbug: Client[0]
      Thread 5 - Content-Encoding: identity, Content-Type: text/xml; charset=utf-8
info: Client[0]
      Thread 5 - GET: https://master.apis.dev.openstreetmap.org/api/0.6/node/964762/3
fail: Client[0]
      Thread 4 - Request failed: NotFound-Not Found
```

**Comment by HarelM** [comment]
What about just printing the response with all the info without printing the request? This way you have a single line with all the info and not two lines.

**Comment by blackboxlogic** [comment]
That sounds like the way to go. Would it help you to have this changed quickly?

**Comment by HarelM** [comment]
It's not urgent for me.

**Comment by HarelM** [comment]
@blackboxlogic Please review my changes. Looking at the logs of my server this what seems to be the right amount of logs to me.
Auth string feels like a hacky solution and might be better with an enum or clientType property or both.

**Comment by blackboxlogic** [comment]
I just removed some of the string manipulation you put in, I hope an extra space at the end of a log line doesn't break anything.

I'd consider using `GetType().Name` instead of having the auth function return a string. This will be the name of the child class, like "NonAuthClient" or "OAuthClient". Would that serve your purpose? Downside: when you request `Get:Node/1234` from an authenticated client, it will look like the call was authenticated even though the request didn't add auth (because it was a `Get`)

![image](https://user-images.githubusercontent.com/31355456/83945438-90a92480-a7d8-11ea-9d9b-ed0bc8bc8878.png)

If you approve, I'll commit the change?

**Comment by HarelM** [comment]
Seems good to me.

**Comment by blackboxlogic** [comment]
I pushed that.
For the record, logs no longer have headers, and no longer have the token for oauth. This is probably a good thing.
