### ISSUE TITLE
Support fetching trace file data by url

### ISSUE THREAD

**Issue by HarelM** [blackboxlogic/OsmApiClient#2]
Looking back at the original code the client derives from `BaseFileFetcher`.
I tried to remember why I did it and the only reason that came to my mind is the ability to get the data of a private trace you uploaded - i.e. when getting the traces list you only get the metadata, but in order to get the gpx file content you need to do another http request.
This is currently handled in my code partially on the client side and partially on the server side - the client get the list of traces, and creates the trace url, when the user clicks on the link the url is sent to the server.
This is less than ideal and a utility method is probably needed in this library to create full url from trace data.
This code basically:
https://github.com/IsraelHikingMap/Site/blob/af5d5d65f4485999571883ebf8315811af79f664/IsraelHiking.Web/sources/application/services/traces.service.ts#L30
And the server code to fetch the file:
https://github.com/IsraelHikingMap/Site/blob/af5d5d65f4485999571883ebf8315811af79f664/IsraelHiking.DataAccess/BaseFileFetcherGateway.cs#L19

**Comment by blackboxlogic** [comment]
I think I just implemented this. Have a look
https://github.com/blackboxlogic/OsmApiClient/blob/bbd97a9ecfe71d40ce3794c1630cb0559b00e424/src/AuthClient.cs#L218

**Comment by HarelM** [comment]
That looks great! The only problem with this implementation is that it assumes the file is actually a GPX file where you can get gzipped (gz extension) file and also gz.bz2.
I had to implement a chain of file converters in order to get the actual content of the trace file.
I'm not sure this is the responsibility of this client and so I think it would be safer to return a stream and let the developer who uses the library decide how to handle this - or maybe not? not sure...

**Comment by blackboxlogic** [comment]
A Stream it is.

**Comment by HarelM** [comment]
I wanted to say yes, but the file name is lost in current implementation:
See here the content disposition usage to get the file name. this is important in order to know how to read the file and how to call it:
https://github.com/IsraelHikingMap/Site/blob/d11d20d9e7b1c2b92e800e421f4045d8b5b56d44/IsraelHiking.DataAccess/BaseFileFetcherGateway.cs#L27
Unfortunately I couldn't find a way to store both the content and the file name in basic .Net objects and so I had to create a wrapper to holed both the file name and the content...
`FileStream` would be ideal except it doesn't support "in memory" files and `MemoryStream` doesn't have a `Name`... :-(
If you find a better solution let me know :-)

**Comment by blackboxlogic** [comment]
The filename I got back is "970.gpx", which is just the traceId and a file extension (not the filename that was provided when the trace was uploaded). The calling code already knows the ID because it was part of the request so the file extension is the only valuable part. I'm looking at the "content type" header which in this case has "{application/gpx+xml}". That seems like it could be useful?
I've added both, without knowing which one is more useful to client code.

**Comment by HarelM** [comment]
Looks great!
Can I try and use this client or we still need @xvik pre release in order to try it out?

**Comment by blackboxlogic** [comment]
I put a fork of OsmSharp as a submodule, so we don't _need_ that merge. I just created [a beta nuget package](https://www.nuget.org/packages/OsmApiClient/0.0.1-beta) which you can try out.

**Comment by HarelM** [comment]
This can probably be closed due to the use of the `TypedStream`.
