### ISSUE TITLE
Default xml deserialization potentially unsafe

### ISSUE THREAD

**Issue by Shkarface** [blackboxlogic/OsmApiClient#25]
### The Problem

The default serializer code uses the stream directly to deserialize xml to target type:
```cs
protected async Task<T> Get<T>(string address, Action<HttpRequestMessage> auth = null) where T : class
{
    var content = await Get(address, auth);
    var stream = await content.ReadAsStreamAsync();
    var serializer = new XmlSerializer(typeof(T));
    var element = serializer.Deserialize(stream) as T;
    return element;
}
```
This does not conform with [(CA5369)](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca5369?view=vs-2019) which states that 

> Deserializing untrusted XML input with XmlSerializer.Deserialize instantiated without an XmlReader object can potentially lead to denial of service, information disclosure, and server-side request forgery attacks. These attacks are enabled by untrusted DTD and XML schema processing, which allows for the inclusion of XML bombs and malicious external entities in the XML. Only with XmlReader is it possible to disable DTD. Inline XML schema processing as XmlReader has the ProhibitDtd and ProcessInlineSchema property set to false by default in .NET Framework version 4.0 and later. The other options such as Stream, TextReader, and XmlSerializationReader cannot disable DTD processing.

### The Solution

Create an xml reader and use it for deserialization:
```cs
protected async Task<T> Get<T>(string address, Action<HttpRequestMessage> auth = null) where T : class
{
    using var content = await Get(address, auth);
    using var stream = await content.ReadAsStreamAsync();
    using var xmlReader = await XmlReader.Create(stream);
    var serializer = new XmlSerializer(typeof(T));
    var element = serializer.Deserialize(xmlReader) as T;
    return element;
}
```

But there is a problem when deserializing OsmChange the create,modify and delete members are empty, I think this has to do with the custom xml reading from OsmSharp.

**Comment by HarelM** [comment]
Thanks for the input.
Feel free to send a PR in both OsmSharp and here to resolve this.
I'm not sure how to fix this... :-/

**Comment by blackboxlogic** [comment]
Thanks for a detailed bug report!

```
Deserializing untrusted XML...
````
The XML comes straight from OSM servers which I trust as much as anything. Unless you're letting end users set the OSM base url, or if we've got a bug that does bad things when composing the request url, or OSM has a a vulnerability, I don't see how the result content would be untrusted.

OsmSharp's XML implementation is a little fragile, so I'm not surprised that `XmlReader` breaks it. I'm sure it's fixable though.

Is there something about your use case, or other context, which makes you not trust the response XML?
