### ISSUE TITLE
Constraints for Bounds.[Min|Max]Latitude in Validate are wrong

### ISSUE THREAD

**Issue by FObermaier** [blackboxlogic/OsmApiClient#26]
Valid latitude values are in the Range [-90, 90]:
https://github.com/blackboxlogic/OsmApiClient/blob/da373dc231103d43dbacc8cc63cf4901ab568535/src/Validate.cs#L16-L23

**Comment by HarelM** [comment]
Can you send a pull request to fix this?

**Comment by HarelM** [comment]
P.S. Are you using our package?

**Comment by blackboxlogic** [comment]
Thanks for noticing this bug. I've just fixed it and I'm **leaning toward not releasing a new version** of the nuget package (because it's so minor), but I would if this is impacting your use-case. Let me know.

**Comment by FObermaier** [comment]
Thanks, not releasing a new package is fine. I'm just investigating if this library can help me with a quick'n dirty utility...
