### ISSUE TITLE
Publish a pre-release nuget package

### ISSUE THREAD

**Issue by blackboxlogic** [blackboxlogic/OsmApiClient#3]
... for testing.
Probably at nuget.org

**Comment by blackboxlogic** [comment]
I learned [how to publish a package](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio)
https://www.nuget.org/packages/OsmApiClient-beta/
No idea if it works.

**Comment by blackboxlogic** [comment]
@HarelM Let me know if you want keys to update/manage the package.

**Comment by blackboxlogic** [comment]
I will occasionally update the package

**Comment by HarelM** [comment]
I think my NuGet user name is Harel.
As a side note, the name and the id of the package should not contain the word beta but instead the version number should, which will indicate NuGet that this is a pre release version.
Look for semver (senantic versioning) on Google.

**Comment by blackboxlogic** [comment]
That published package is ahead of what is checked-in to git because it is using a version of OsmSharp that hasn't been merged yet. I'll try to work more cleanly.
