### ISSUE TITLE
Can't install OsmApiClient in nuget - VS2022

### ISSUE THREAD

**Issue by elr0berto** [blackboxlogic/OsmApiClient#34]
Unable to find a version of 'OsmSharp' that is compatible with 'OsmApiClient 0.0.7 constraint: OsmSharp (>= 7.0.0-pre014)'.

**Comment by blackboxlogic** [comment]
See https://www.nuget.org/packages/OsmSharp/#versions-body-tab

You'll need to check this box in nuget package manager:
![image](https://user-images.githubusercontent.com/31355456/182423954-b4e5194b-0a8c-4f32-bdbd-4f9eb87b6230.png)

I wish OsmSharp with release a proper 7.0.0 so I didn't need to reference a pre-release, I'm sure they have their reasons.

**Comment by elr0berto** [comment]
Ok, thanks for the quick support!
