### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by HarelM** [blackboxlogic/OsmApiClient#37]
Should we archive this repo?
If so we need to change the readme to link to the new location of this repo and only afterwards archive it.
I've got a notification from NuGet that my token is about to expire, which makes sense, since it wasn't used for almost a year.
@blackboxlogic what do you think?

**Comment by blackboxlogic** [comment]
Yep. I updated the readme and deprecated [the nuget package](https://www.nuget.org/packages/OsmApiClient/).
