### ISSUE TITLE
Test OAuth

### ISSUE THREAD

**Issue by blackboxlogic** [blackboxlogic/OsmApiClient#5]
Create OAuth tests in the functional test project.

**Comment by blackboxlogic** [comment]
Create OAuth tests in the functional test project.

**Comment by blackboxlogic** [comment]
@HarelM can I leave this to you? If you add OAuth creds in OsmApiClient\FunctionalTests\appsettings.json and run the project, it'll give you an answer. Note that this does make map changes as the user, so keep it to the DEV OSM instance.

**Comment by HarelM** [comment]
@blackboxlogic Sure, I have assigned it to me.

**Comment by HarelM** [comment]
I have fixed what needed to be fixed with small changes to the code. Most of it seems to be working as expected, I don't have a user which uses a full permissions oauth client, but the test I've made are sufficient.
