### ISSUE TITLE
Logging and Error Handling

### ISSUE THREAD

**Issue by blackboxlogic** [blackboxlogic/OsmApiClient#6]
There is currently no logging and error handling is crude.

**Comment by HarelM** [comment]
I think logging should use the `Microsoft.Extensions.Logging`'s `ILogger` and allow the developer to inject his own logger either on instance creation or some sort of static method.

**Comment by blackboxlogic** [comment]
What should be logged? My thoughts:
- Http requests url, including parameters, excluding credentials
- A notice that the request completed successfully
- Details of any errors
I don't think we should log:
- Content of a request
- Content of a response

**Comment by HarelM** [comment]
Sounds about right, much like what asp.net is writing to the log when a request arrives.

**Comment by blackboxlogic** [comment]
Regarding DI for `Ilogger`, putting it as a parameter of the constructor makes it required, where really this feature can run without a logger just fine. Thoughts?
- Overloaded constructors (I've heard bad things about DI and overloaded constructors)
- Don't put it in the constructor, put it as a property with a public setter (I don't think this works well with Core's DI framework)
- Yeah it's required.
- Something else?

**Comment by HarelM** [comment]
See #12 - use factory. The factory should be part of the DI as the client is content dependant.
