### ISSUE TITLE
Show license and give credit

### ISSUE THREAD

**Issue by blackboxlogic** [blackboxlogic/OsmApiClient#7]
I'We should probably show a license and give credit to developers or projects that have contributed.

**Comment by HarelM** [comment]
I think MIT license is probably the right way to go.

**Comment by blackboxlogic** [comment]
I'm looking at OsmSharp as an example: https://github.com/OsmSharp/core/blob/master/LICENSE.md
Should there be a statement limiting liability? (I think yes)
Should there be a copyright notice? (I think yes) If yes do you want your name on it?

**Comment by HarelM** [comment]
There was an option in Github to automatically add a license file, I think...
In any case, sure, feel free to add my name: Harel Mazor

**Comment by blackboxlogic** [comment]
I've added license information to the repository and the nuget package.
